<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MineEditor.Core</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ubiety.Nbt" Version="0.1.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MineEditor.Core.Tests" />
  </ItemGroup>

</Project>
